### ISSUE TITLE
Not able to use extension

### ISSUE THREAD

**Issue by provkritika** [NeverVane/html-email-preview#1]
I have installed and enabled extension in VSCode but what is the next step. How to use it as I can't see anything related in command pallette

**Comment by NeverVane** [comment]
> I have installed and enabled extension in VSCode but what is the next step. How to use it as I can't see anything related in command pallette

you have to command:
- Set API Key
- Get Preview

once you set the API key you’ll be able to send the second command and get the html code preview

**Comment by casscors** [comment]
After buying a key and inputting it into extension settings, and attempting to restart the extension as well as VS Code, running both commands results in an error.

command 'html-email-preview.setApiKey' not found
command 'html-email-preview.fetchDevices' not found

**Comment by NeverVane** [comment]
How are you trying to run the commands ?

In order to run the commands you need to:

- press CTRL + Shift + P
- select the command to run 
---> Set API Key
---> Show Preview

(remember that an html file needs to be opened in the editor in order to run successfully )


Can you confirm you're taking the above specified actions ?

**Comment by LarsKuijlenburg** [comment]
I'm having the same issue, And am performing the steps like you described them above

**Comment by LarsKuijlenburg** [comment]
I think I might've found the issue. When I have the VSCode devtools open, it's complaining about being unable to find the `axios` module when trying to preview an email. That might cause these commands to break. 

Looks like it's a missing dependency, as I don't see axios anywhere in the `package.json`

**Comment by NeverVane** [comment]
added missing dependency and pushed new version to VS Code Marketplace

**Comment by LarsKuijlenburg** [comment]
Can confirm it works for me now! Thanks for the update

**Comment by travismathews** [comment]
Sorry to necro an old issue, I would recommend we add this to the readme.  It took me a bit to figure out how to set it up and I had to dig to find this issue.

**Comment by oliveratgithub** [comment]
> In order to run the commands you need to:
> 
> * press CTRL + Shift + P
> * select the command to run
>   ---> Set API Key
>   ---> Show Preview
> 
> (remember that an html file needs to be opened in the editor in order to run successfully )

@NeverVane you should really put this in the Extension description / FAQ. Like others, I was totally lost in how I can get it to work, and the first instruction remark «_Various devices / clients to choose from_» kept me searching & searching for where I can have a "Device selection" as part of any possible Preview option in VSCode…

**Comment by NeverVane** [comment]
I will for sure add that,
thanks pointing it out
