### ISSUE TITLE
Html rendering on ios mail is different than real device

### ISSUE THREAD

**Issue by hithamalbasheir** [NeverVane/html-email-preview#4]
I'm testing adding box-shadow on an email template, it works on the preview on ios mail, but on real device, the shadow doesn't show up, can you double check this please

**Comment by NeverVane** [comment]
Hi, let me check.
It would be useful if you could provide the html you’re testing and also the device/client key in order to try the same device.

**Comment by hithamalbasheir** [comment]
Sure, this is how it looked like on actual iPhone 
![IMG-20240619-WA0004](https://github.com/NeverVane/html-email-preview/assets/38975111/5606fa29-e3ed-4595-94e9-4f3d4810e56e)
And this is how it looks like on the preview
<img width="788" alt="Screenshot 2024-06-20 at 11 43 48 PM" src="https://github.com/NeverVane/html-email-preview/assets/38975111/9d71a786-438d-49c7-82a5-34435b622832">
 
 And this is the html file
 `
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml">

<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title></title>
    <style>
        div:empty {
            display: none
        }

        body {
            background: #E5E5E5;
            font-family: Arial;
            font-style: normal;
        }

        .header {
            height: 70px;
            box-shadow: 0px 4px 20px 0px rgba(0, 0, 0, 0.08);
            background-color: {{data.companyHeaderColor}};
            padding: 20px 0;
        }

        a {

            color: inherit;
        }


        .wrapper {
            width: 60%;
            height: auto;
            margin: 5% auto;
            background: #FFFFFF;
            border: 1px solid #F9F9F9;
            box-shadow: 2px -3px 4px rgba(0, 0, 0, 0.1);
        }

        .template-content {
            padding: 10%;
        }

        .message {
            color: #424242;
        }

        .greeting {
            font-size: 24px;
            color: #000000;
            font-weight: bold;
        }


        .footer {
            height: 30%;
            border-radius: 0px 0px 5px 5px;
            padding-bottom: 10px;
            background-color: {{data.companyFooterColor}};
            background-image: url("{{data.companyFooter}}");
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        }

        @media only screen and (max-width: 768px) {
            .wrapper {
                width: 100%;
            }

            .message {
                font-size: 12px;
                line-height: 20px;
            }

        }
    </style>
</head>

<body
    style="background-color:#E5E5E5;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;font-family:Arial;font-style:normal;padding:5%;">
    <div class="wrapper"
        style="height:auto;margin-right:auto;margin-left:auto;background-color:#FFFFFF;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;border-radius:5px;border-width:1px;border-style:solid;border-color:#F9F9F9;box-shadow:2px -3px 4px rgba(0, 0, 0, 0.1);">
        <div class="header">
            <img src="{{data.companyHeader}}" style="{{data.headerStyle}}">
        </div>

        <div class="template-content" style="padding-top:10%;padding-bottom:10%;padding-right:10%;padding-left:10%;">
            <div class="message">
                Hey Lovely Human,<br />
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                A new coaching session has been booked from the website. Please find the details for the same below-
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                <b>Full name</b> : {{data.fullName}}
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                <b>Email of booker</b> : {{data.email}}
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                <b>Mentor(s) booked</b> : {{data.mentors}}
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                <b>Email of Mentor(s)</b> : {{data.mentorsEmail}}
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                <b>Preferred date</b> : {{data.preparedDate}}
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                <b>Preferred time</b> : {{data.preparedTime}}
            </div>

            <div class="message" style="margin-top:25px;margin-bottom:20px;margin-right:0;margin-left:0;color:#424242;">
                Please reply back to {{data.email}} as soon as possible to confirm the Talk Show.
            </div>

        </div>



        <div class="footer">
            {{data.logo}}
            {{data.address}}
            {{data.footerIcons}}
        </div>
        <div style="display:none">{{data.unique_id}}</div>

    </div>
</body>

</html>
`

**Comment by NeverVane** [comment]
Please allow me some time. I will reply asap

**Comment by NeverVane** [comment]
Hi @hithamalbasheir , could you please specify if you're using default Email client on your iOS device or anything else ?

**Comment by hithamalbasheir** [comment]
Hi @NeverVane, apparently I got confused when I received the photo and thought it's from iOS Mail app, but I think it's from Gmail app, where shadow is not supported according to [this](https://www.caniemail.com/) website
Apologies for the confusion and nice work on the email preview tool 🙌
