### ISSUE TITLE
Authentication Issue in Postman

### ISSUE THREAD

**Issue by samueljacobs98** [NeverVane/html-email-preview#5]
Hi,

I have tried using the API via Postman with the following request:
POST
https://emailpreview.h501.io/sendPreview
X-API-KEY: ...
Content-Type: application/json

```json
{
    "htmlBody": "<h2>Your HTML goes here</h2>",
    "emailSubject": "Some cool stuff",
    "devices": [
        "microsoft_outlook_2016"
    ]
}
```

and the response, despite displaying `status: 200`, the response body says "Authentication failed with third-party API.".

<img width="920" alt="Screenshot 2024-07-24 at 10 55 45" src="https://github.com/user-attachments/assets/d16a6345-14cb-4a32-93ba-0b6f165fc175">

I am not sure how Authentication could be an issue when using the header `X-API-KEY` with the value of the APIKey in the `APIKey.txt` file provided upon purchase.

**Comment by NeverVane** [comment]
Hi, thanks for reaching out.
Could you please tell me when you made the purchase so that I can identify your key and make some test ?

**Comment by samueljacobs98** [comment]
about an hour ago

**Comment by samueljacobs98** [comment]
I've got it working using the same API key with the VSCode extension, but it would be very useful to be able to get it to work with Postman as well.

**Comment by NeverVane** [comment]
I will see how to make that working smoothly too
