### ISSUE TITLE
How to cancel API key subscription?

### ISSUE THREAD

**Issue by jayrsmith** [NeverVane/html-email-preview#6]
Hi, can you please let me know how to cancel my subscription?

Thanks

**Comment by NeverVane** [comment]
Hi, please open a ticket at https://my.h501.io and provide API Key

**Comment by jayrsmith** [comment]
@NeverVane Thanks, but I don't want to have to register an account just to cancel the subscription. I tried the contact link from my.h501.io but it 404s (https://h501.io/en/contact).

Can you let me know how else to get this done please.

**Comment by NeverVane** [comment]
well in order for me to help, you need to provide API key, which I guess you don't want to paste here publicly, so:
a) you open a ticket
b) use the contact details page, which works fine on our end

**Comment by jayrsmith** [comment]
Fair enough. Registered and submitted.

**Comment by NeverVane** [comment]
The subscription has been canceled as per your request.
Thanks :)
