### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by Jayageeth** [NeverVane/html-email-preview#7]
![image](https://github.com/user-attachments/assets/afc84d1d-f20b-4b6f-ba13-138ec7643fa4)

Hi, Im getting this issue when trying to run in vs code, i have purchased the api key and when trying to run it its showing me like this
Can you help me fix it?

**Comment by NeverVane** [comment]
Hi, what command are you issuing?

**Comment by NeverVane** [comment]
I'm looking at the logs and the only issue happened around your ticket time is related to Stripe gateway. Could you please clarify if you received your API Key ?

**Comment by Jayageeth** [comment]
Hi, Yes i have received the API Key

**Comment by Jayageeth** [comment]
Something wrong with the Extension i guess, do check it bro

**Comment by NeverVane** [comment]
Hi there, I tried a couple of times yesterday and today too. Everything went smooth.
Have you tried again after the error?

**Comment by Jayageeth** [comment]
yes have tried multiple times. Can we connect over Microsoft Teams or any other apps?
so that i can share my screen and show you!

**Comment by NeverVane** [comment]
Could you please attach the recording here ?
Also make sure the API Key is correctly set before proceeding with the preview.

**Comment by Jayageeth** [comment]
Hi Bro, here is the video link
https://drive.google.com/drive/folders/1Y4y8pEJJvn0cybqrTtIiIUuTZ-YT0Em5?usp=sharing

**Comment by NeverVane** [comment]
well, it turned out that your API key is disabled. that's the reason :)
it looks like Stripe callback didn't work as expected. I will dig into the issue.

meanwhile I will send you a new key to the email used with Stripe ( I will also delete this one as it was shown publicly ).
