### ISSUE TITLE
The VS Code extension seems to down

### ISSUE THREAD

**Issue by alexbudin** [NeverVane/html-email-preview#8]
seems the service does not work anymore and a new website has just appeared (https://mailfly.io)

https://emailpreview.h501.io/ is redirecting now to that and the VS Code extension is no longer working.

API is down as well

Any news? how can we cancel if this doesnt work anymore?

**Comment by NeverVane** [comment]
Hi, the service is still working.
The redirect you see is because the website has been restyled and moved to a new domain, but APIs still run on https://emailpreview.h501.io/ .

Can you provide more details on the issues you're going through ?

**Comment by alexbudin** [comment]
Well its just came back ;) because the API urls where redirecting to the new website, so clearly someone fixed it :) seems to be ok now.

it initially redirected for a few hours and then it started showing 401 errors and now its ok again

this was the error that it showed in the last 2 hours up until a few minutes before your comment.
<img width="464" alt="image" src="https://github.com/user-attachments/assets/8ef7e1ba-298b-4e65-b0c0-b40050bace4f">

**Comment by alexbudin** [comment]
can you please explain what will happen now, since there is a new website and the cost was $3 / month ? will i be charged $24 automatically now? There is no explanation for all this and i tried creating an account with the email i put in initially but nothing appears there, no API key no account info....its all very confusing

**Comment by NeverVane** [comment]
I very much doubt that calling API endpoints ( https://emailpreview.h501.io/devices https://emailpreview.h501.io/sendPreview ) was giving you a redirect to https://mailfly.io , different story for https://emailpreview.h501.io which correctly redirects to https://mailfly.io .

**Comment by NeverVane** [comment]
Regarding the cost change, you should have received an email explaining the cost change.
If you want to cancel your subscription you can tell me to do so and it will be done.

**Comment by alexbudin** [comment]
Now the preview image comes empty:

<img width="834" alt="image" src="https://github.com/user-attachments/assets/1ac02b63-68ac-4a8a-a6ad-f75f217249a1">

**Comment by NeverVane** [comment]
I'm investigating what happened, I will let you asap

**Comment by NeverVane** [comment]
The issue is now solved. 
I had an issue with a rendering agent.

Let me know

**Comment by ashutosh11019** [comment]
Hi @NeverVane
I want to use this preview. Can you share your email id. so we can contact.

**Comment by NeverVane** [comment]
> Hi @NeverVane I want to use this preview. Can you share your email id. so we can contact.

You can reach me out at mailfly@h501.io
